runtime:         go113

handlers:
- url:           /robots.txt
  static_files:  robots.txt
  upload:        robots.txt
  secure:        always
  http_headers:
    Strict-Transport-Security: 'max-age=63072000; includeSubDomains; preload'

- url:           /(.*\.(json|js|map))$
  static_files:  \1
  upload:        .*\.(json|js|map)$
  secure:        always
  expiration:    "0"
  mime_type:     "application/javascript"
  http_headers:
    Strict-Transport-Security: 'max-age=63072000; includeSubDomains; preload'

- url:           /images
  static_dir:    images
  secure:        always
  http_headers:
    Strict-Transport-Security: 'max-age=63072000; includeSubDomains; preload'

- url:           /.*
  script:        auto
  secure:        always
